# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
        exclude: ^(3rd|doc)\/
    -   id: end-of-file-fixer
        exclude: ^(3rd|doc)\/
    -   id: check-added-large-files
-   repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.4.0
    hooks:
      - id: golangci-lint
        args:
            - "--fix"
      - id: go-mod-tidy
